In [48]:
import pandas as pd
import numpy as np

In [49]:
#Levantamos la base de datos.
df = pd.ExcelFile('DataBase\homicidios.xlsx')

In [50]:
hechos_h = pd.read_excel(df, 'HECHOS')
victimas_h = pd.read_excel(df,'VICTIMAS')

In [51]:
#Revisamos el tipo de datos de los dataframes. Primero "hechos_h".
hechos_h.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 696 entries, 0 to 695
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     696 non-null    object
 1   N_VICTIMAS             696 non-null    int64
 2   FECHA                  696 non-null    datetime64[ns]
 3   AAAA                   696 non-null    int64
 4   MM                     696 non-null    int64
 5   DD                     696 non-null    int64
 6   HORA                   696 non-null    object
 7   HH                     696 non-null    object
 8   LUGAR_DEL_HECHO        696 non-null    object
 9   TIPO_DE_CALLE          696 non-null    object
 10  Calle                  695 non-null    object
 11  Altura                 129 non-null    float64
 12  Cruce                  525 non-null    object
 13  Dirección Normalizada  688 non-null    object
 14  COMUNA                 696 non-null    int64
 15  XY (CABA)              696 non-null    object
 16  pos x                  696 non-null    object
 17  pos y                  696 non-null    object
 18  PARTICIPANTES          696 non-null    object
 19  VICTIMA                696 non-null    object
 20  ACUSADO                696 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(5), object(14)
memory usage: 114.3+ KB

In [52]:
#Luego "victimas_h"
victimas_h.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_hecho             717 non-null    object
 1   FECHA                717 non-null    datetime64[ns]
 2   AAAA                 717 non-null    int64
 3   MM                   717 non-null    int64
 4   DD                   717 non-null    int64
 5   ROL                  717 non-null    object
 6   VICTIMA              717 non-null    object
 7   SEXO                 717 non-null    object
 8   EDAD                 717 non-null    object
 9   FECHA_FALLECIMIENTO  717 non-null    object
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 56.1+ KB

In [53]:
victimas_h = victimas_h.rename(columns={'ID_hecho':'ID'})

In [54]:
df_combinado = hechos_h.merge(victimas_h, on='ID', how='inner')

In [55]:
df_combinado

,ID,N_VICTIMAS,FECHA_x,AAAA_x,MM_x,DD_x,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,ACUSADO,FECHA_y,AAAA_y,MM_y,DD_y,ROL,VICTIMA_y,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,AUTO,2016-01-01,2016,1,1,CONDUCTOR,MOTO,MASCULINO,19,2016-01-01 00:00:00
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,PASAJEROS,2016-01-02,2016,1,2,CONDUCTOR,AUTO,MASCULINO,70,2016-01-02 00:00:00
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AV ENTRE RIOS 2034,AVENIDA,...,AUTO,2016-01-03,2016,1,3,CONDUCTOR,MOTO,MASCULINO,30,2016-01-03 00:00:00
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,SD,2016-01-10,2016,1,10,CONDUCTOR,MOTO,MASCULINO,18,SD
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,PASAJEROS,2016-01-21,2016,1,21,CONDUCTOR,MOTO,MASCULINO,29,2016-02-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17,AV. RIESTRA Y MOM,AVENIDA,...,AUTO,2021-12-13,2021,12,13,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,18,2021-12-18 00:00:00
713,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1,AU DELLEPIANE Y LACARRA,AUTOPISTA,...,AUTO,2021-12-20,2021,12,20,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,43,2021-12-20 00:00:00
714,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0,AV. GAONA Y TERRADA,AVENIDA,...,CARGAS,2021-12-30,2021,12,30,CONDUCTOR,MOTO,MASCULINO,27,2022-01-02 00:00:00
715,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10,AV. EVA PERON 4071,AVENIDA,...,CARGAS,2021-12-15,2021,12,15,CONDUCTOR,AUTO,MASCULINO,60,2021-12-20 00:00:00
716,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6,PADRE CARLOS MUJICA 709,CALLE,...,AUTO,2021-11-18,2021,11,18,CICLISTA,BICICLETA,MASCULINO,53,2021-11-19 00:00:00

In [56]:
df_combinado.dtypes

ID                               object
N_VICTIMAS                        int64
FECHA_x                  datetime64[ns]
AAAA_x                            int64
MM_x                              int64
DD_x                              int64
HORA                             object
HH                               object
LUGAR_DEL_HECHO                  object
TIPO_DE_CALLE                    object
Calle                            object
Altura                          float64
Cruce                            object
Dirección Normalizada            object
COMUNA                            int64
XY (CABA)                        object
pos x                            object
pos y                            object
PARTICIPANTES                    object
VICTIMA_x                        object
ACUSADO                          object
FECHA_y                  datetime64[ns]
AAAA_y                            int64
MM_y                              int64
DD_y                              int64
ROL                              object
VICTIMA_y                        object
SEXO                             object
EDAD                             object
FECHA_FALLECIMIENTO              object
dtype: object

In [57]:
#Creo una funcion para poder distinguir las columnas duplicadas.

def encontrar_columnas_duplicadas(df):
    columnas_unicas = []
    columnas_duplicadas = []

    for i, columna1 in enumerate(df.columns[:-1]):
        for columna2 in df.columns[i+1:]:
            if (df[columna1] == df[columna2]).all():
                columnas_duplicadas.append((columna1, columna2))
            else:
                columnas_unicas.append((columna1, columna2))

    return columnas_duplicadas, columnas_unicas

#Corro la funcion.
columnas_duplicadas, columnas_unicas = encontrar_columnas_duplicadas(df_combinado)

#Como solo nos interesan las columnas que se repiten, solo imprimimos estas
# de modo tal que sea facil eliminarlas.
print("Pares de columnas iguales:")
for columna1, columna2 in columnas_duplicadas:
    print(f"{columna1} y {columna2} son iguales")

Pares de columnas iguales:
AAAA_x y AAAA_y son iguales
MM_x y MM_y son iguales

In [58]:
#Eliminamos las columnas que tienen valores duplicados luego del 'join'.

df_combinado = df_combinado.drop(['AAAA_y','MM_y'], axis=1)

In [59]:
#Con lo visto anteriormente deberiamos tener las columnas 'DD', 'FECHA', 'VICTIMA' iguales,
# ya que son las columnas con el mismo nombre a las cuales se les agrega la 'x' o la 'y' para 
# identificarlas, pero no salen en la lista asi que vamos a checkear.

filas = []
for index, row in df_combinado[['FECHA_x','FECHA_y','DD_x','DD_y','VICTIMA_x','VICTIMA_y']].iterrows():
    if row['FECHA_x'] !=row['FECHA_y']:
        filas.append(index)
    if row['DD_x'] !=row['DD_y']:
        filas.append(index)
    if row['VICTIMA_x'] !=row['VICTIMA_y']:
        filas.append(index)

#Imprimimos las filas que no se repiten.

print(filas)

[65, 204, 204, 237, 238, 602, 603]

In [60]:
#Imprimimos los valores de las columnas que checkeamos recien.
df_combinado[['FECHA_x','FECHA_y', 'DD_x','DD_y', 'VICTIMA_x',  'VICTIMA_y']].iloc[filas]

       FECHA_x    FECHA_y  DD_x  DD_y    VICTIMA_x VICTIMA_y
65  2016-07-02 2016-07-03     3     3         MOTO      MOTO
204 2017-05-24 2017-05-29    24    29         MOTO      MOTO
204 2017-05-24 2017-05-29    24    29         MOTO      MOTO
237 2017-09-02 2017-09-02     2     2  OBJETO FIJO      AUTO
238 2017-09-02 2017-09-02     2     2  OBJETO FIJO      AUTO
602 2020-12-05 2020-12-05     5     5  PEATON_MOTO    PEATON
603 2020-12-05 2020-12-05     5     5  PEATON_MOTO      MOTO

In [61]:
#Como podemos ver las discrepancias en los valores de las columnas son minimas.


# En cuanto a las columnas "FECHA" y "DD", teniendo en cuenta que tenemos unificadas las 
# tablas de hechos y victimas la diferencia puede ser del hecho al dia de fallecimiento,
# y como para este trabajo nos interesan los hechos fatales para las mediciones a realizar,
# dejaremos las fechas de la tabla victimas que tiene los datos de los fallecimientos.

df_combinado = df_combinado.drop(['DD_x','FECHA_x'], axis=1)

In [62]:
# En cuanto a la diferencia de las columnas "VICTIMA" vemos en la fila 237 y 238 que se trata
#  probablemente de un error de TYPO, ya que un objeto fijo no puede ser una victima mientras 
# que puede ser la causa del accidente. En cuanto a las filas 602 y 603, tenemos, probablemente
# el mismo error pero ya no siendo la causa sino que se ha escrito en la columna "VICTIMA" el 
# dato de los "PARTICIPANTES" del hecho. Por esto pasamos a checkear esas columnas en las filas
# nombradas anteriormente.

filas2 = []
df_combinado[['PARTICIPANTES', 'ACUSADO']].iloc[[237,238,602,603]]

        PARTICIPANTES ACUSADO
237  AUTO-OBJETO FIJO    AUTO
238  AUTO-OBJETO FIJO    AUTO
602  PEATON_MOTO-MOTO    MOTO
603  PEATON_MOTO-MOTO    MOTO

In [63]:
#Cargamos los datos a los que queremos generarles cambios.
filas1 = 237, 238
filas2 = 602,603
acusado = 'OBJETO FIJO'
partic = 'PEATON-MOTO'

# Utilizar .at[] para cambiar el valor en las columnas
df_combinado.at[filas1, 'ACUSADO'] = acusado
df_combinado.at[filas2, 'PARTICIPANTES'] = partic

In [64]:
#Imprimimos las filas para corroborar los cambios.
df_combinado[['FECHA_y','DD_y', 'VICTIMA_x',  'VICTIMA_y', 'PARTICIPANTES','ACUSADO']].iloc[filas]

       FECHA_y  DD_y    VICTIMA_x VICTIMA_y     PARTICIPANTES      ACUSADO
65  2016-07-03     3         MOTO      MOTO  MOTO-OBJETO FIJO  OBJETO FIJO
204 2017-05-29    29         MOTO      MOTO           MOTO-SD           SD
204 2017-05-29    29         MOTO      MOTO           MOTO-SD           SD
237 2017-09-02     2  OBJETO FIJO      AUTO  AUTO-OBJETO FIJO  OBJETO FIJO
238 2017-09-02     2  OBJETO FIJO      AUTO  AUTO-OBJETO FIJO  OBJETO FIJO
602 2020-12-05     5  PEATON_MOTO    PEATON       PEATON-MOTO         MOTO
603 2020-12-05     5  PEATON_MOTO      MOTO       PEATON-MOTO         MOTO

In [65]:
#Vemos que solo queda una discrepancia queda en la fila 603 donde tenemos en la 
# columna 'VICTIMA_y' el valor 'MOTO' cuando deberia ser 'PEATON' ya que como vimos
# en la columna participantes los involucrados son un peaton y una moto, y no dos
# motos como figuraria en el dataframe, asi que realizamos ese cambio de la misma manera.

fila = 603
victima = 'PEATON'

df_combinado.at[fila, 'VICTIMA_y'] = victima

In [66]:
#Corroboramos una vez mas antes de eliminar las columnas que no necesitamos.
df_combinado[['FECHA_y','DD_y', 'VICTIMA_x',  'VICTIMA_y', 'PARTICIPANTES','ACUSADO']].iloc[filas]

       FECHA_y  DD_y    VICTIMA_x VICTIMA_y     PARTICIPANTES      ACUSADO
65  2016-07-03     3         MOTO      MOTO  MOTO-OBJETO FIJO  OBJETO FIJO
204 2017-05-29    29         MOTO      MOTO           MOTO-SD           SD
204 2017-05-29    29         MOTO      MOTO           MOTO-SD           SD
237 2017-09-02     2  OBJETO FIJO      AUTO  AUTO-OBJETO FIJO  OBJETO FIJO
238 2017-09-02     2  OBJETO FIJO      AUTO  AUTO-OBJETO FIJO  OBJETO FIJO
602 2020-12-05     5  PEATON_MOTO    PEATON       PEATON-MOTO         MOTO
603 2020-12-05     5  PEATON_MOTO    PEATON       PEATON-MOTO         MOTO

In [67]:
#Habiendo corregido todo eliminamos la columna con los datos erroneos.

df_combinado = df_combinado.drop('VICTIMA_x', axis=1)

In [68]:
#Creamos una funcion para reorganizar las direcciones de la columna "LUGAR DEL HECHO"

def reorg_direcc(address):
    words = address.split()
    if "Av." in words:
        words.remove("Av.")
        words = ["Av."] + words
    return " ".join(words)

df_combinado['LUGAR_DEL_HECHO'] = df_combinado['LUGAR_DEL_HECHO'].apply(reorg_direcc)

In [69]:
df_combinado

,ID,N_VICTIMAS,AAAA_x,MM_x,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,Calle,Altura,...,pos y,PARTICIPANTES,ACUSADO,FECHA_y,DD_y,ROL,VICTIMA_y,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,1,2016,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,PIEDRA BUENA AV.,NaN,...,-34.68757022,MOTO-AUTO,AUTO,2016-01-01,1,CONDUCTOR,MOTO,MASCULINO,19,2016-01-01 00:00:00
1,2016-0002,1,2016,1,01:15:00,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,"PAZ, GRAL. AV.",NaN,...,-34.66977709,AUTO-PASAJEROS,PASAJEROS,2016-01-02,2,CONDUCTOR,AUTO,MASCULINO,70,2016-01-02 00:00:00
2,2016-0003,1,2016,1,07:00:00,7,AV ENTRE RIOS 2034,AVENIDA,ENTRE RIOS AV.,2034.0,...,-34.63189362,MOTO-AUTO,AUTO,2016-01-03,3,CONDUCTOR,MOTO,MASCULINO,30,2016-01-03 00:00:00
3,2016-0004,1,2016,1,00:00:00,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,LARRAZABAL AV.,NaN,...,-34.68092974,MOTO-SD,SD,2016-01-10,10,CONDUCTOR,MOTO,MASCULINO,18,SD
4,2016-0005,1,2016,1,05:20:00,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,SAN JUAN AV.,NaN,...,-34.62246630,MOTO-PASAJEROS,PASAJEROS,2016-01-21,21,CONDUCTOR,MOTO,MASCULINO,29,2016-02-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,2021-0093,1,2021,12,17:10:00,17,AV. RIESTRA Y MOM,AVENIDA,RIESTRA AV.,NaN,...,-34.64561636,MOTO-AUTO,AUTO,2021-12-13,13,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,18,2021-12-18 00:00:00
713,2021-0094,1,2021,12,01:10:00,1,AU DELLEPIANE Y LACARRA,AUTOPISTA,"DELLEPIANE, LUIS, TTE. GRAL.",NaN,...,-34.65117757,MOTO-AUTO,AUTO,2021-12-20,20,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,43,2021-12-20 00:00:00
714,2021-0095,1,2021,12,00:43:00,0,AV. GAONA Y TERRADA,AVENIDA,GAONA AV.,NaN,...,-34.61984745,MOTO-CARGAS,CARGAS,2021-12-30,30,CONDUCTOR,MOTO,MASCULINO,27,2022-01-02 00:00:00
715,2021-0096,1,2021,12,10:30:00,10,AV. EVA PERON 4071,AVENIDA,"PERON, EVA AV.",4071.0,...,-34.65021673,AUTO-CARGAS,CARGAS,2021-12-15,15,CONDUCTOR,AUTO,MASCULINO,60,2021-12-20 00:00:00
716,2021-0097,1,2021,11,06:10:00,6,PADRE CARLOS MUJICA 709,CALLE,PADRE CARLOS MUJICA,709.0,...,-34.58679619,BICICLETA-AUTO,AUTO,2021-11-18,18,CICLISTA,BICICLETA,MASCULINO,53,2021-11-19 00:00:00

In [70]:
# Hacemos un conteo de los valores "SD" del dataframe.

conteo_sd = df_combinado.apply(lambda x: x.value_counts().get('SD', 0))

print(conteo_sd)

ID                        0
N_VICTIMAS                0
AAAA_x                    0
MM_x                      0
HORA                      1
HH                        1
LUGAR_DEL_HECHO           1
TIPO_DE_CALLE             0
Calle                     0
Altura                    0
Cruce                     0
Dirección Normalizada     0
COMUNA                    0
XY (CABA)                 0
pos x                     0
pos y                     0
PARTICIPANTES             0
ACUSADO                  23
FECHA_y                   0
DD_y                      0
ROL                      11
VICTIMA_y                 9
SEXO                      6
EDAD                     53
FECHA_FALLECIMIENTO      68
dtype: int64

In [71]:
#Seguimos corrigiendo los valores de la columna "LUGAR DEL HECHO"
df_combinado['LUGAR_DEL_HECHO'] =df_combinado['LUGAR_DEL_HECHO'].str.replace(',', '')

In [72]:
df_combinado

,ID,N_VICTIMAS,AAAA_x,MM_x,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,Calle,Altura,...,pos y,PARTICIPANTES,ACUSADO,FECHA_y,DD_y,ROL,VICTIMA_y,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,1,2016,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,PIEDRA BUENA AV.,NaN,...,-34.68757022,MOTO-AUTO,AUTO,2016-01-01,1,CONDUCTOR,MOTO,MASCULINO,19,2016-01-01 00:00:00
1,2016-0002,1,2016,1,01:15:00,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,"PAZ, GRAL. AV.",NaN,...,-34.66977709,AUTO-PASAJEROS,PASAJEROS,2016-01-02,2,CONDUCTOR,AUTO,MASCULINO,70,2016-01-02 00:00:00
2,2016-0003,1,2016,1,07:00:00,7,AV ENTRE RIOS 2034,AVENIDA,ENTRE RIOS AV.,2034.0,...,-34.63189362,MOTO-AUTO,AUTO,2016-01-03,3,CONDUCTOR,MOTO,MASCULINO,30,2016-01-03 00:00:00
3,2016-0004,1,2016,1,00:00:00,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,LARRAZABAL AV.,NaN,...,-34.68092974,MOTO-SD,SD,2016-01-10,10,CONDUCTOR,MOTO,MASCULINO,18,SD
4,2016-0005,1,2016,1,05:20:00,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,SAN JUAN AV.,NaN,...,-34.62246630,MOTO-PASAJEROS,PASAJEROS,2016-01-21,21,CONDUCTOR,MOTO,MASCULINO,29,2016-02-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,2021-0093,1,2021,12,17:10:00,17,AV. RIESTRA Y MOM,AVENIDA,RIESTRA AV.,NaN,...,-34.64561636,MOTO-AUTO,AUTO,2021-12-13,13,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,18,2021-12-18 00:00:00
713,2021-0094,1,2021,12,01:10:00,1,AU DELLEPIANE Y LACARRA,AUTOPISTA,"DELLEPIANE, LUIS, TTE. GRAL.",NaN,...,-34.65117757,MOTO-AUTO,AUTO,2021-12-20,20,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,43,2021-12-20 00:00:00
714,2021-0095,1,2021,12,00:43:00,0,AV. GAONA Y TERRADA,AVENIDA,GAONA AV.,NaN,...,-34.61984745,MOTO-CARGAS,CARGAS,2021-12-30,30,CONDUCTOR,MOTO,MASCULINO,27,2022-01-02 00:00:00
715,2021-0096,1,2021,12,10:30:00,10,AV. EVA PERON 4071,AVENIDA,"PERON, EVA AV.",4071.0,...,-34.65021673,AUTO-CARGAS,CARGAS,2021-12-15,15,CONDUCTOR,AUTO,MASCULINO,60,2021-12-20 00:00:00
716,2021-0097,1,2021,11,06:10:00,6,PADRE CARLOS MUJICA 709,CALLE,PADRE CARLOS MUJICA,709.0,...,-34.58679619,BICICLETA-AUTO,AUTO,2021-11-18,18,CICLISTA,BICICLETA,MASCULINO,53,2021-11-19 00:00:00

In [73]:
#Ahora checkeamos las columnas del dataframe, para luego dejar solo las que nos hacen falta.
df_combinado.columns

Index(['ID', 'N_VICTIMAS', 'AAAA_x', 'MM_x', 'HORA', 'HH', 'LUGAR_DEL_HECHO',
       'TIPO_DE_CALLE', 'Calle', 'Altura', 'Cruce', 'Dirección Normalizada',
       'COMUNA', 'XY (CABA)', 'pos x', 'pos y', 'PARTICIPANTES', 'ACUSADO',
       'FECHA_y', 'DD_y', 'ROL', 'VICTIMA_y', 'SEXO', 'EDAD',
       'FECHA_FALLECIMIENTO'],
      dtype='object')

In [74]:
#Borramos las que no nos hacen falta.

df_combinado = df_combinado.drop(['AAAA_x','MM_x','DD_y','Calle','XY (CABA)','Altura','Cruce','Dirección Normalizada'], axis=1)

In [75]:
#Formateamos correctamente las columnas para normalizar las mayusculas.

df_combinado['ID'] = df_combinado['ID'].str.title()
df_combinado['ROL'] = df_combinado['ROL'].str.title()
df_combinado['VICTIMA_y'] = df_combinado['VICTIMA_y'].str.title()
df_combinado['SEXO'] = df_combinado['SEXO'].str.title()
df_combinado['LUGAR_DEL_HECHO'] = df_combinado['LUGAR_DEL_HECHO'].str.title()
df_combinado['TIPO_DE_CALLE'] = df_combinado['TIPO_DE_CALLE'].str.title()
df_combinado['pos x'] = df_combinado['pos x'].str.title()
df_combinado['pos y'] = df_combinado['pos y'].str.title()
df_combinado['PARTICIPANTES'] = df_combinado['PARTICIPANTES'].str.title()
df_combinado['ACUSADO'] = df_combinado['ACUSADO'].str.title()
df_combinado['ROL'] = df_combinado['ROL'].str.title()

In [76]:
 # Renombramos algunas columnas que quedaron con el nombre cambiado por el JOIN.


df_combinado = df_combinado.rename(columns={'VICTIMA_y': 'VICTIMA'})
df_combinado = df_combinado.rename(columns={'FECHA_y': 'FECHA'})

In [77]:
# Quitamos del dataframe a las filas con faltantes en las columnas principales.

df_combinado = df_combinado[(df_combinado['PARTICIPANTES'] != 'Sd') & (df_combinado['VICTIMA'] != 'Sd') & (df_combinado['ACUSADO'] != 'Sd')]

In [78]:
# Hacemos un conteo de los valores "SD" del dataframe.

conteo_sd = df_combinado.apply(lambda x: x.value_counts().get('SD', 0))

print(conteo_sd)

ID                      0
N_VICTIMAS              0
HORA                    1
HH                      1
LUGAR_DEL_HECHO         0
TIPO_DE_CALLE           0
COMUNA                  0
pos x                   0
pos y                   0
PARTICIPANTES           0
ACUSADO                 0
FECHA                   0
ROL                     0
VICTIMA                 0
SEXO                    0
EDAD                   45
FECHA_FALLECIMIENTO    53
dtype: int64

In [79]:
df_combinado

,ID,N_VICTIMAS,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,COMUNA,pos x,pos y,PARTICIPANTES,ACUSADO,FECHA,ROL,VICTIMA,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,1,04:00:00,4,Av Piedra Buena Y Av Fernandez De La Cruz,Avenida,8,-58.47533969,-34.68757022,Moto-Auto,Auto,2016-01-01,Conductor,Moto,Masculino,19,2016-01-01 00:00:00
1,2016-0002,1,01:15:00,1,Av Gral Paz Y Av De Los Corrales,Gral Paz,9,-58.50877521,-34.66977709,Auto-Pasajeros,Pasajeros,2016-01-02,Conductor,Auto,Masculino,70,2016-01-02 00:00:00
2,2016-0003,1,07:00:00,7,Av Entre Rios 2034,Avenida,1,-58.39040293,-34.63189362,Moto-Auto,Auto,2016-01-03,Conductor,Moto,Masculino,30,2016-01-03 00:00:00
4,2016-0005,1,05:20:00,5,Av San Juan Y Presidente Luis Saenz Peña,Avenida,1,-58.38718297,-34.62246630,Moto-Pasajeros,Pasajeros,2016-01-21,Conductor,Moto,Masculino,29,2016-02-01 00:00:00
5,2016-0008,1,18:30:00,18,Av 27 De Febrero Y Av Escalada,Avenida,8,-58.44451316,-34.68475866,Moto-Objeto Fijo,Objeto Fijo,2016-01-24,Conductor,Moto,Masculino,30,2016-01-24 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,2021-0093,1,17:10:00,17,Av. Riestra Y Mom,Avenida,7,-58.43353773,-34.64561636,Moto-Auto,Auto,2021-12-13,Pasajero_Acompañante,Moto,Femenino,18,2021-12-18 00:00:00
713,2021-0094,1,01:10:00,1,Au Dellepiane Y Lacarra,Autopista,9,-58.46739825,-34.65117757,Moto-Auto,Auto,2021-12-20,Pasajero_Acompañante,Moto,Femenino,43,2021-12-20 00:00:00
714,2021-0095,1,00:43:00,0,Av. Gaona Y Terrada,Avenida,11,-58.47293407,-34.61984745,Moto-Cargas,Cargas,2021-12-30,Conductor,Moto,Masculino,27,2022-01-02 00:00:00
715,2021-0096,1,10:30:00,10,Av. Eva Peron 4071,Avenida,9,-58.47066794,-34.65021673,Auto-Cargas,Cargas,2021-12-15,Conductor,Auto,Masculino,60,2021-12-20 00:00:00
716,2021-0097,1,06:10:00,6,Padre Carlos Mujica 709,Calle,1,-58.37976155,-34.58679619,Bicicleta-Auto,Auto,2021-11-18,Ciclista,Bicicleta,Masculino,53,2021-11-19 00:00:00

In [80]:
#Como hay faltantes en la columna de "FECHA FALLECIMIENTO", se va a rellenar con la columna "FECHA".
# Para esto, pasamos el formato a 'str' para facilitar la tarea.

df_combinado['FECHA_FALLECIMIENTO'] = df_combinado['FECHA_FALLECIMIENTO'].astype(str)
df_combinado['FECHA'] = df_combinado['FECHA'].astype(str)
df_combinado.loc[df_combinado['FECHA_FALLECIMIENTO'] == 'SD', 'FECHA_FALLECIMIENTO'] = df_combinado['FECHA']
df_combinado['FECHA_FALLECIMIENTO'] = df_combinado['FECHA_FALLECIMIENTO'].str.replace('T', ' ')

In [81]:
#Para evitar malentendidos renombramos algunas columnas.

df_combinado = df_combinado.rename(columns={'HORA': 'HORA_ACCIDENTE'})
df_combinado = df_combinado.rename(columns={'FECHA': 'FECHA_ACCIDENTE'})
df_combinado = df_combinado.rename(columns={'pos x': 'LONGITUD'})
df_combinado = df_combinado.rename(columns={'pos y': 'LATITUD'})

In [82]:
# Extraer las horas y minutos de las cadenas de texto
df_combinado['HORA'] = df_combinado['HORA_ACCIDENTE'].str.split(':').str[0]
df_combinado['MINUTO'] = df_combinado['HORA_ACCIDENTE'].str.split(':').str[1]

# Se convierten las horas y minutos a números
df_combinado['HORA'] = pd.to_numeric(df_combinado['HORA'], errors='coerce')
df_combinado['MINUTO'] = pd.to_numeric(df_combinado['MINUTO'], errors='coerce')

# Calculamos la media de las horas y minutos.
mean_hora = df_combinado['HORA'].mean()
mean_minuto = df_combinado['MINUTO'].mean()

# Crear la media de la hora como una cadena de texto
mean_time = f"{int(mean_hora)}:{int(mean_minuto)}"

# Reemplazamos los valores "SD" y "Sd" con la media de la hora, que creamos antes.
df_combinado.loc[df_combinado['HORA_ACCIDENTE'] == 'SD', 'HORA_ACCIDENTE'] = mean_time
df_combinado.loc[df_combinado['HORA_ACCIDENTE'] == 'Sd', 'HORA_ACCIDENTE'] = mean_time

#Ahora se eliminan las columnas 'HORA' y 'MINUTO'
df_combinado = df_combinado.drop(columns=['HORA', 'MINUTO'])

In [83]:
df_combinado

,ID,N_VICTIMAS,HORA_ACCIDENTE,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,COMUNA,LONGITUD,LATITUD,PARTICIPANTES,ACUSADO,FECHA_ACCIDENTE,ROL,VICTIMA,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,1,04:00:00,4,Av Piedra Buena Y Av Fernandez De La Cruz,Avenida,8,-58.47533969,-34.68757022,Moto-Auto,Auto,2016-01-01,Conductor,Moto,Masculino,19,2016-01-01 00:00:00
1,2016-0002,1,01:15:00,1,Av Gral Paz Y Av De Los Corrales,Gral Paz,9,-58.50877521,-34.66977709,Auto-Pasajeros,Pasajeros,2016-01-02,Conductor,Auto,Masculino,70,2016-01-02 00:00:00
2,2016-0003,1,07:00:00,7,Av Entre Rios 2034,Avenida,1,-58.39040293,-34.63189362,Moto-Auto,Auto,2016-01-03,Conductor,Moto,Masculino,30,2016-01-03 00:00:00
4,2016-0005,1,05:20:00,5,Av San Juan Y Presidente Luis Saenz Peña,Avenida,1,-58.38718297,-34.62246630,Moto-Pasajeros,Pasajeros,2016-01-21,Conductor,Moto,Masculino,29,2016-02-01 00:00:00
5,2016-0008,1,18:30:00,18,Av 27 De Febrero Y Av Escalada,Avenida,8,-58.44451316,-34.68475866,Moto-Objeto Fijo,Objeto Fijo,2016-01-24,Conductor,Moto,Masculino,30,2016-01-24 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,2021-0093,1,17:10:00,17,Av. Riestra Y Mom,Avenida,7,-58.43353773,-34.64561636,Moto-Auto,Auto,2021-12-13,Pasajero_Acompañante,Moto,Femenino,18,2021-12-18 00:00:00
713,2021-0094,1,01:10:00,1,Au Dellepiane Y Lacarra,Autopista,9,-58.46739825,-34.65117757,Moto-Auto,Auto,2021-12-20,Pasajero_Acompañante,Moto,Femenino,43,2021-12-20 00:00:00
714,2021-0095,1,00:43:00,0,Av. Gaona Y Terrada,Avenida,11,-58.47293407,-34.61984745,Moto-Cargas,Cargas,2021-12-30,Conductor,Moto,Masculino,27,2022-01-02 00:00:00
715,2021-0096,1,10:30:00,10,Av. Eva Peron 4071,Avenida,9,-58.47066794,-34.65021673,Auto-Cargas,Cargas,2021-12-15,Conductor,Auto,Masculino,60,2021-12-20 00:00:00
716,2021-0097,1,06:10:00,6,Padre Carlos Mujica 709,Calle,1,-58.37976155,-34.58679619,Bicicleta-Auto,Auto,2021-11-18,Ciclista,Bicicleta,Masculino,53,2021-11-19 00:00:00

In [84]:
#Le damos formato fecha a la columna "FECHA_ACCIDENTE" para poder sacar el semestre en el que ocurrio.
df_combinado['FECHA_ACCIDENTE'] = pd.to_datetime(df_combinado['FECHA_ACCIDENTE'])

In [85]:
# Ahora creamos la columna "SEMESTRE" y de acuerdo al mes de "FECHA_ACCIDENTE" completamos los valores.
df_combinado['SEMESTRE'] = [1 if month <= 6 else 2 for month in df_combinado['FECHA_ACCIDENTE'].dt.month]

In [86]:
# Creamos la columna "ANIO" para facilitar el calculo del KPI

df_combinado['ANIO'] = df_combinado['FECHA_ACCIDENTE'].dt.year

In [87]:
#Eliminamos la columna "HH" ya que no aporta nada.
df_combinado = df_combinado.drop(['HH'], axis=1)

In [91]:
#Formateamos en formato numerico la columna "EDAD". Dejando los valores "SD" como nulos.

df_combinado['EDAD'] = pd.to_numeric(df_combinado['EDAD'], errors='coerce')

# Calculamos la media de la columna edad para poder completar los datos faltantes de la misma.

mean_edad = df_combinado['EDAD'].mean()
mean_edad = int(mean_edad)

#Ahora rellenamos los nulos con la media de la edad.

df_combinado['EDAD'] = df_combinado['EDAD'].fillna(mean_edad)

#Ahora formateamos los valores de la columna para que queden numeros enteros.

df_combinado['EDAD'] = df_combinado['EDAD'].astype(int)

In [92]:
df_combinado

,ID,N_VICTIMAS,HORA_ACCIDENTE,LUGAR_DEL_HECHO,TIPO_DE_CALLE,COMUNA,LONGITUD,LATITUD,PARTICIPANTES,ACUSADO,FECHA_ACCIDENTE,ROL,VICTIMA,SEXO,EDAD,FECHA_FALLECIMIENTO,SEMESTRE,ANIO
0,2016-0001,1,04:00:00,Av Piedra Buena Y Av Fernandez De La Cruz,Avenida,8,-58.47533969,-34.68757022,Moto-Auto,Auto,2016-01-01,Conductor,Moto,Masculino,19,2016-01-01 00:00:00,1,2016
1,2016-0002,1,01:15:00,Av Gral Paz Y Av De Los Corrales,Gral Paz,9,-58.50877521,-34.66977709,Auto-Pasajeros,Pasajeros,2016-01-02,Conductor,Auto,Masculino,70,2016-01-02 00:00:00,1,2016
2,2016-0003,1,07:00:00,Av Entre Rios 2034,Avenida,1,-58.39040293,-34.63189362,Moto-Auto,Auto,2016-01-03,Conductor,Moto,Masculino,30,2016-01-03 00:00:00,1,2016
4,2016-0005,1,05:20:00,Av San Juan Y Presidente Luis Saenz Peña,Avenida,1,-58.38718297,-34.62246630,Moto-Pasajeros,Pasajeros,2016-01-21,Conductor,Moto,Masculino,29,2016-02-01 00:00:00,1,2016
5,2016-0008,1,18:30:00,Av 27 De Febrero Y Av Escalada,Avenida,8,-58.44451316,-34.68475866,Moto-Objeto Fijo,Objeto Fijo,2016-01-24,Conductor,Moto,Masculino,30,2016-01-24 00:00:00,1,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,2021-0093,1,17:10:00,Av. Riestra Y Mom,Avenida,7,-58.43353773,-34.64561636,Moto-Auto,Auto,2021-12-13,Pasajero_Acompañante,Moto,Femenino,18,2021-12-18 00:00:00,2,2021
713,2021-0094,1,01:10:00,Au Dellepiane Y Lacarra,Autopista,9,-58.46739825,-34.65117757,Moto-Auto,Auto,2021-12-20,Pasajero_Acompañante,Moto,Femenino,43,2021-12-20 00:00:00,2,2021
714,2021-0095,1,00:43:00,Av. Gaona Y Terrada,Avenida,11,-58.47293407,-34.61984745,Moto-Cargas,Cargas,2021-12-30,Conductor,Moto,Masculino,27,2022-01-02 00:00:00,2,2021
715,2021-0096,1,10:30:00,Av. Eva Peron 4071,Avenida,9,-58.47066794,-34.65021673,Auto-Cargas,Cargas,2021-12-15,Conductor,Auto,Masculino,60,2021-12-20 00:00:00,2,2021
716,2021-0097,1,06:10:00,Padre Carlos Mujica 709,Calle,1,-58.37976155,-34.58679619,Bicicleta-Auto,Auto,2021-11-18,Ciclista,Bicicleta,Masculino,53,2021-11-19 00:00:00,2,2021

In [93]:
#Guardamos el archivo final.
df_combinado.to_csv('DataBase/homicidios_final.csv', index=False)